// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 23DashBoard

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageDashboard = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageDashboard, &ui_img_942215904);
    lv_obj_set_width(ui_ImageDashboard, LV_SIZE_CONTENT);   /// 233
    lv_obj_set_height(ui_ImageDashboard, LV_SIZE_CONTENT);    /// 233
    lv_obj_set_x(ui_ImageDashboard, -86);
    lv_obj_set_y(ui_ImageDashboard, -4);
    lv_obj_set_align(ui_ImageDashboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageDashboard, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageDashboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageNeedle = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageNeedle, &ui_img_1601502596);
    lv_obj_set_width(ui_ImageNeedle, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_ImageNeedle, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_x(ui_ImageNeedle, -86);
    lv_obj_set_y(ui_ImageNeedle, 71);
    lv_obj_set_align(ui_ImageNeedle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageNeedle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageNeedle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImageNeedle, 10, -30);
    lv_img_set_angle(ui_ImageNeedle, 2500);

    ui_ImageLight = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageLight, &ui_img_light_png);
    lv_obj_set_width(ui_ImageLight, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageLight, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageLight, 4);
    lv_obj_set_y(ui_ImageLight, 93);
    lv_obj_set_align(ui_ImageLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageSfatyBelt = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageSfatyBelt, &ui_img_safety_belt_png);
    lv_obj_set_width(ui_ImageSfatyBelt, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageSfatyBelt, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageSfatyBelt, 154);
    lv_obj_set_y(ui_ImageSfatyBelt, 93);
    lv_obj_set_align(ui_ImageSfatyBelt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSfatyBelt, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSfatyBelt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWatertemp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageWatertemp, &ui_img_temp_gray_png);
    lv_obj_set_width(ui_ImageWatertemp, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageWatertemp, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageWatertemp, 104);
    lv_obj_set_y(ui_ImageWatertemp, 93);
    lv_obj_set_align(ui_ImageWatertemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWatertemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWatertemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageTurnlight = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageTurnlight, &ui_img_turn_light_png);
    lv_obj_set_width(ui_ImageTurnlight, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageTurnlight, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageTurnlight, 54);
    lv_obj_set_y(ui_ImageTurnlight, 93);
    lv_obj_set_align(ui_ImageTurnlight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageTurnlight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageTurnlight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDate = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate, 125);
    lv_obj_set_y(ui_LabelDate, -68);
    lv_obj_set_align(ui_LabelDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDate, "2025-1-10");
    lv_obj_set_style_text_color(ui_LabelDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDate, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, 125);
    lv_obj_set_y(ui_LabelTime, -34);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "23:00");
    lv_obj_set_style_text_color(ui_LabelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTime, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);


}

#define COLOR_RED   		0xff,0x0,0x0
#define COLOR_WHITE   	0xff,0xff,0xff
#define COLOR_YELLOW   	0xff,0xff,0x0

 void ui_set_date_time_value(uint8_t *date_str, uint8_t * time_str)
{
			lv_label_set_text(ui_LabelTime, time_str);	
			lv_label_set_text(ui_LabelDate, date_str);	
}

void ui_set_rpm_angle(uint32_t angle)
{
	lv_img_set_angle(ui_ImageNeedle, angle*2500/100);
}


void ui_set_water_temp_color( uint32_t color)
{
		lv_color_t color_value;
		if(color == 0)
		{
				color_value = lv_color_make(COLOR_WHITE);	
				lv_obj_set_style_img_recolor(ui_ImageWatertemp, color_value, 0);
				lv_obj_set_style_img_recolor_opa(ui_ImageWatertemp, 255, 0);				
		}
		else
		{
				color_value = lv_color_make(COLOR_RED);	
				lv_obj_set_style_img_recolor(ui_ImageWatertemp, color_value, 0);
				lv_obj_set_style_img_recolor_opa(ui_ImageWatertemp, 255, 0);				
		}
}

void ui_set_safty_belt_color( uint32_t color)
{
		lv_color_t color_value;
		if(color == 0)
		{
				color_value = lv_color_make(COLOR_WHITE);	
				lv_obj_set_style_img_recolor(ui_ImageSfatyBelt, color_value, 0);
				lv_obj_set_style_img_recolor_opa(ui_ImageSfatyBelt, 255, 0);				
		}
		else
		{
				color_value = lv_color_make(COLOR_RED);	
				lv_obj_set_style_img_recolor(ui_ImageSfatyBelt, color_value, 0);
				lv_obj_set_style_img_recolor_opa(ui_ImageSfatyBelt, 255, 0);				
		}
}

void ui_set_light_color( uint32_t color)
{
		lv_color_t color_value;
		if(color == 0)
		{
				color_value = lv_color_make(COLOR_WHITE);	
				lv_obj_set_style_img_recolor(ui_ImageLight, color_value, 0);
				lv_obj_set_style_img_recolor_opa(ui_ImageLight, 255, 0);				
		}
		else if(color == 2)
		{
				color_value = lv_color_make(COLOR_RED);	
				lv_obj_set_style_img_recolor(ui_ImageLight, color_value, 0);
				lv_obj_set_style_img_recolor_opa(ui_ImageLight, 255, 0);				
		}
		else	
		{
				color_value = lv_color_make(COLOR_YELLOW);	
				lv_obj_set_style_img_recolor(ui_ImageLight, color_value, 0);
				lv_obj_set_style_img_recolor_opa(ui_ImageLight, 255, 0);					
		}
}

void ui_set_turn_light_color( uint32_t color)
{
		lv_color_t color_value;
		if(color == 0)
		{
				color_value = lv_color_make(COLOR_WHITE);	
				lv_obj_set_style_img_recolor(ui_ImageTurnlight, color_value, 0);
				lv_obj_set_style_img_recolor_opa(ui_ImageTurnlight, 255, 0);				
		}
		else
		{
				color_value = lv_color_make(COLOR_RED);	
				lv_obj_set_style_img_recolor(ui_ImageTurnlight, color_value, 0);
				lv_obj_set_style_img_recolor_opa(ui_ImageTurnlight, 255, 0);				
		}	
}




