// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 23DashBoard

#ifndef _23DASHBOARD_UI_H
#define _23DASHBOARD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ImageDashboard;
extern lv_obj_t * ui_ImageNeedle;
extern lv_obj_t * ui_ImageLight;
extern lv_obj_t * ui_ImageSfatyBelt;
extern lv_obj_t * ui_ImageWatertemp;
extern lv_obj_t * ui_ImageTurnlight;
extern lv_obj_t * ui_LabelDate;
extern lv_obj_t * ui_LabelTime;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_942215904);    // assets/gauge-bg.png
LV_IMG_DECLARE(ui_img_1601502596);    // assets/gauge-needle.png
LV_IMG_DECLARE(ui_img_light_png);    // assets/Light.png
LV_IMG_DECLARE(ui_img_safety_belt_png);    // assets/safety_belt.png
LV_IMG_DECLARE(ui_img_temp_gray_png);    // assets/temp_gray.png
LV_IMG_DECLARE(ui_img_turn_light_png);    // assets/turn_light.png

void ui_set_date_time_value(uint8_t *date_str, uint8_t * time_str);
void ui_set_rpm_angle(uint32_t angle);
void ui_set_water_temp_color( uint32_t color);
void ui_set_safty_belt_color( uint32_t color);
void ui_set_light_color( uint32_t color);
void ui_set_turn_light_color( uint32_t color);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
